### ISSUE TITLE
Page breaks when I press back after navigating to a link that is shared

### ISSUE THREAD

**Issue by shatanikmahanty** [lukepighetti/fluro#198]
If I have a link example.com/eventDetails/16252. I share the link to somebody and he clicks it it opens properly but on back press it goes to example.com/eventDetails which does not exist in my case. Please help me fix this if there is a way in Fluro.

This is how a defined the route in actual program : 
```
router.define(
      '/eventDetails/:id',
      transitionType: TransitionType.materialFullScreenDialog,
      handler: Handler(handlerFunc: (_, params) {
        String id = params["id"]?.first;
        return EventDetail(
          id: id,
        );
      }),
    );
```
And this is for route not found. I tried using my own logic to fix this. If the url ends with "/eventDetails" it will go to homepage but this doesnot seem to be working  
 ```
router.notFoundHandler = Handler(handlerFunc: (context, params) {
      debugPrint("ROUTE WAS NOT FOUND !!!");
      if (window.location.href.endsWith("/eventDetails") ||
          window.location.href.endsWith("/destinationDetails") ||
          window.location.href.endsWith("/reserveDestination") ||
          window.location.href.endsWith("/artistDetails") ||
          window.location.href.endsWith("/artistReserve")) {
        window.location.href = "/home";
        return Home();
      }else {
        return RouteNotFound("");
      }
    });
```

I think this is happening because the route is going to --> initial route --> /eventDetails --> /eventDetails/:id

This also happens when you refresh a page with parameters

**Comment by lukepighetti** [comment]
This is a limitation in core Flutter. If your first route is `/foo/bar/baz` it will try to push `/foo` under `/foo/bar` under `/foo/bar/baz`.

**Comment by shatanikmahanty** [comment]
> This is a limitation in core Flutter. If your first route is `/foo/bar/baz` it will try to push `/foo` under `/foo/bar` under `/foo/bar/baz`.

Thanks for explaining 👍

**Comment by mkivanova** [comment]
I had the same concern and there is a way around it! looking at https://sellsbrothers.com/understanding-flutter-deep-links-on-the-web -> Flutter does indeed attempt to add a navigation entry for each segment but if the route generator returns `null` for a specific route, it will not get added to the nav tree. 

Let's say you have defined `/foo` and `/foo/bar/baz/` routes, but **not** `/foo/bar`. When Flutter attempts to add `/foo/bar` fluro will default to a `notFoundHandler`, and I think there's further defaulting just in case, so that it always returns a page route builder.

A way around it is to explicitly create an AppRoute for the missing one:
`static final badRoute = AppRoute('/foo/bar', null);`

then updating fluro's `matchRoute`:
```
    AppRouteMatch? match = _routeTree.matchRoute(path!);
    AppRoute? route = match?.route;

    // NEW - custom code to prevent flutter from adding a default handler
    if (route != null && route.handler == null) {
      return RouteMatch(
          matchType: RouteMatchType.noMatch,
          errorMessage: "This route should not be auto-added");
    }
```

Unfortunately that means that if someone directly hits `/foo/bar` they won't get the `notFoundHandler`. Flutter seems to redirect to the `/` in that scenario which works for me at the moment.

@lukepighetti it's not super clean but may be something to consider adding in some way.
