### ISSUE TITLE
Sometime it's necessary pass to Route Object no only String

### ISSUE THREAD

**Issue by pjcau** [lukepighetti/fluro#46]
Hi guy, 

I'm using some this framework so now i need in general use pass Object no only String.
Look this library, i think there are some cod to change but i think start from this definition:

`typedef Widget HandlerFunc(BuildContext context, Map<String, List<Object>> parameters);
`  

What do you think it ?

J

**Comment by ycaxgjd** [comment]
You could define one Dict instead

**Comment by CedSW** [comment]
Hi, I'm having the same problem - need to pass an object. Can I get little bit more information or example how to achieve that? Thank you

**Comment by OsmanBrito** [comment]
#65 solved my problem.

**Comment by lukef** [comment]
I'm in the process of converting fluro to using a different mechanism for dealing with parameters. Once I do this it'll probably be a v2.0 kind of change though.

The TLDR is (something like):
```dart
usersRouteCallback(Parameters parameters, dynamic context) {
  int userId = parameters.firstInt("id");
  ...
  return userId;
}
```

I have separated out the routing logic so that it's more generic and able to be reused. You can take a sneak peek of the generic (engine) here: https://github.com/theyakka/dazza.

**Comment by Nisthar** [comment]
Any updates on this?

**Comment by xhp281** [comment]
Any updates on this?

**Comment by lukepighetti** [comment]
You can now pass custom RouteSettings with arguments https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb
